server:
  port: 8123
spring:
  profiles:
    active: local
langchain4j:
  openai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_APIKEY}
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
#配置目录输出级别为debug
#logging:
#  level:
#    root: debug